name: Simple Workflow

on:
    workflow_dispatch:

jobs:

    TEST_JOB_01:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1 COPYING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
